---
  markdown: kramdown
  blog_base: "/blog/"
  blog_title: "HTTP Notes"
  blog_subtitle: "News and resources from the HTTP community"
  blog_id: "tag:httpworkshop.org,2020-06-30:/blog//1"
  blog_image_url: "https://httpworkshop.org/asset/http_workshop.png"
  permalink: /blog/:year/:month/:day/:title

  sass:
      sass_dir: _scss
